---
- include: sudo.yml

- name: Iinstall Apache + mod_wsgi
  action: yum
          name=$item
          state=present
  with_items:
    - httpd
    - mod_wsgi
  notify: Restart Apache

- include: config.yml

- name: Enable Apache Service
  action: service name=httpd enabled=yes
