---
- include: sudo.yml
- include: repo.yml

- name: Install 4store
  action: yum
          name=4store
          state=present

- name: Setup 4store backend
  action: command
          4s-backend-setup DefaultKB
  notify: Restart 4store
