---
- name: Download ez_setup.py
  action: get_url
          url=https://bitbucket.org/pypa/setuptools/raw/0.8/ez_setup.py
          dest=/usr/local/src/ez_setup.py

- name: Install setuptools
  action: command
          chdir=/usr/local/src
          creates=/usr/local/bin/easy_install
          /usr/local/bin/python2.7 ez_setup.py

- name: Download get_pip.py
  action: get_url
          url=https://raw.github.com/pypa/pip/master/contrib/get-pip.py
          dest=/usr/local/src/get_pip.py

- name: Install pip
  action: command
          chdir=/usr/local/src
          creates=/usr/local/bin/pip
          /usr/local/bin/python2.7 get_pip.py
